import Foundation

/// Murmur's take on Wispr Flow's "Voice Profile": a persona derived from the
/// user's actual dictations — what they talk about and how they phrase it —
/// generated by the on-device model and refreshed as usage grows.
struct VoiceProfile: Codable, Equatable {
    var title: String
    var summary: String
    /// Short style tags (`.chip-row`), e.g. "Detailed", "Frequent pauses".
    /// Optional so profiles saved before this field existed still decode.
    var traits: [String]?
    /// Total dictated words when this profile was generated; used to decide
    /// when enough new material justifies a refresh.
    var wordCountAtGeneration: Int

    /// One line describing how this person actually writes, for use as
    /// model context. The profile was previously generated and then only
    /// displayed; this is what lets it feed the rewrites and answers that
    /// are supposed to sound like the user.
    var voiceContext: String {
        var line = summary
        if let traits, !traits.isEmpty {
            line += " Characteristic traits: \(traits.joined(separator: ", "))."
        }
        return line
    }
}

enum VoiceProfileStore {
    private static let key = "voiceProfile"
    /// Regenerate after this many new words have been dictated.
    static let refreshThreshold = 250
    /// Minimum material before the first profile.
    static let minimumWords = 80

    static func load() -> VoiceProfile? {
        guard let data = UserDefaults.standard.data(forKey: key),
              let profile = try? JSONDecoder().decode(VoiceProfile.self, from: data)
        else { return nil }
        return profile
    }

    static func save(_ profile: VoiceProfile) {
        if let data = try? JSONEncoder().encode(profile) {
            UserDefaults.standard.set(data, forKey: key)
        }
    }

    static func shouldRefresh(totalWords: Int) -> Bool {
        guard totalWords >= minimumWords else { return false }
        guard let existing = load() else { return true }
        return totalWords - existing.wordCountAtGeneration >= refreshThreshold
    }

    /// Builds the persona from recent transcripts using the on-device model.
    static func generate(
        from entries: [HistoryEntry],
        totalWords: Int,
        engine: RewriteEngine) async -> VoiceProfile? {
        guard engine.isAvailable else { return nil }

        let samples = entries.prefix(30).map(\.text).joined(separator: "\n")
        let clipped = String(samples.prefix(4000))
        guard !clipped.isEmpty else { return nil }

        let instructions = """
        You will receive samples of one person's dictated speech. Invent a \
        short, fun two-word persona title that captures what they talk about \
        and how they speak (examples of the format: "Design Inspector", \
        "Pipeline Poet", "Deadline Whisperer"). Then write one short sentence \
        (max 14 words) describing their dictation style. Then list exactly \
        three short style tags (one to three words each, e.g. "Detailed", \
        "Frequent pauses", "Clarifies often"), comma-separated. Answer in \
        exactly this format, nothing else:
        Title: <two word title>
        Style: <one sentence>
        Traits: <tag>, <tag>, <tag>
        """
        do {
            let reply = try await engine.rewrite(clipped, instructions: instructions)
            var title = ""
            var summary = ""
            var traits: [String] = []
            for line in reply.components(separatedBy: "\n") {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.lowercased().hasPrefix("title:") {
                    title = String(trimmed.dropFirst(6))
                        .trimmingCharacters(in: .whitespaces)
                        .trimmingCharacters(in: CharacterSet(charactersIn: "\"“”."))
                } else if trimmed.lowercased().hasPrefix("style:") {
                    summary = String(trimmed.dropFirst(6))
                        .trimmingCharacters(in: .whitespaces)
                } else if trimmed.lowercased().hasPrefix("traits:") {
                    traits = String(trimmed.dropFirst(7))
                        .components(separatedBy: ",")
                        .map { $0.trimmingCharacters(in: .whitespaces)
                            .trimmingCharacters(in: CharacterSet(charactersIn: "\"“”.")) }
                        .filter { !$0.isEmpty }
                }
            }
            guard !title.isEmpty, title.count <= 40 else { return nil }
            let profile = VoiceProfile(
                title: title, summary: summary,
                traits: traits.isEmpty ? nil : traits,
                wordCountAtGeneration: totalWords)
            save(profile)
            return profile
        } catch {
            return nil
        }
    }
}
